CREATE TABLE IF NOT EXISTS pozicija(
	id_pozicija  INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
	,pozicija VARCHAR(91) NOT NULL
);

INSERT INTO pozicija(id_pozicija, pozicija)
VALUES (1, "klet");
INSERT INTO
pozicija(id_pozicija, pozicija)
VALUES (2, "dnevna");
INSERT INTO
pozicija(id_pozicija, pozicija)
VALUES (3, "adrian");
INSERT INTO
pozicija(id_pozicija, pozicija)
VALUES (4, "oci");
INSERT INTO
pozicija(id_pozicija, pozicija)
VALUES (5, "leila");
