CREATE TABLE IF NOT EXISTS jezik(
	id_jezik  INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
	,jezik VARCHAR(91) NOT NULL
);
INSERT INTO jezik(id_jezik, jezik)
VALUES (1, "slovenščina");
INSERT INTO jezik(id_jezik, jezik)
VALUES (2, "angleščina");
INSERT INTO jezik(id_jezik, jezik)
VALUES (3, "hrvaščina");
INSERT INTO jezik(id_jezik, jezik)
VALUES (4, "francoščina");
INSERT INTO jezik(id_jezik, jezik)
VALUES (5, "italijanščina");
	
