CREATE TABLE IF NOT EXISTS podrocje(
	id_podrocje INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT
	,podrocje VARCHAR(91) NOT NULL
);
INSERT INTO podrocje(podrocje)
VALUES ("slo leposlovje");
INSERT INTO podrocje(podrocje)
VALUES ("tuje leposlovje");
INSERT INTO podrocje(podrocje)
VALUES ("otroško");
INSERT INTO podrocje(podrocje)
VALUES ("dramatika");
INSERT INTO podrocje(podrocje)
VALUES ("poezija");
INSERT INTO podrocje(podrocje)
VALUES ("družboslovje");
INSERT INTO podrocje(podrocje)
VALUES ("jezikoslovje");
INSERT INTO podrocje(podrocje)
VALUES ("naravoslovje");
INSERT INTO podrocje(podrocje)
VALUES ("dom");
INSERT INTO podrocje(podrocje)
VALUES ("drugo");
